// DO NOT EDIT. This file is generated by `fresh`.
// This file SHOULD be checked into source version control.
// To update this file, run `fresh manifest`.

import * as $0 from "./routes/byCountry/[country].tsx";
import * as $1 from "./routes/fav.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/map.tsx";
import * as $4 from "./routes/search.tsx";
import * as $5 from "./routes/top.tsx";
import * as $$0 from "./islands/FavStations.tsx";
import * as $$1 from "./islands/StatioMain.tsx";
import * as $$2 from "./islands/StationSearch.tsx";
import * as $$3 from "./islands/TopStations.tsx";

const manifest = {
  routes: {
    "./routes/byCountry/[country].tsx": $0,
    "./routes/fav.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/map.tsx": $3,
    "./routes/search.tsx": $4,
    "./routes/top.tsx": $5,
  },
  islands: {
    "./islands/FavStations.tsx": $$0,
    "./islands/StatioMain.tsx": $$1,
    "./islands/StationSearch.tsx": $$2,
    "./islands/TopStations.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
