// Script to compile static/map.ts to static/map.js
// Run after any changes to static/map.ts
// deno task compile-map
import { emit } from "@/scripts/deps.ts";

const compileMap = async () => {
  const emitResult = await emit("static_server/map.ts");

  const mapJs = emitResult[
    Object.keys(emitResult).find((k) => k.includes("static_server/map.ts"))!
  ];

  const warning = "// This file is generated by compileMap.ts";
  await Deno.writeTextFile("static/map.js", `${warning}\n${mapJs}`);
};

await compileMap();
